version: 2

jobs:

  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: cd ~ && wget https://github.com/goreleaser/goreleaser/releases/download/v0.117.0/goreleaser_amd64.deb && sudo dpkg -i goreleaser_amd64.deb
      - run: sudo apt-get install -y rpm
      - run: ./mage test
      - run: ./mage release
      - store_artifacts:
          path: ./dist
          destination: build
